name: aem_env
channels:
  - conda-forge
dependencies:
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2025.11.12=h4c7d964_0
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - liblzma=5.8.1=h2466b09_2
  - libsqlite=3.51.1=hf5d6505_0
  - libzlib=1.3.1=h2466b09_2
  - openssl=3.6.0=h725018a_0
  - pip=25.3=pyh8b19718_0
  - python=3.10.19=hc20f281_2_cpython
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=h2c6b04d_3
  - ucrt=10.0.26100.0=h57928b3_0
  - vc=14.3=h2b53caa_33
  - vc14_runtime=14.44.35208=h818238b_33
  - vcomp14=14.44.35208=h818238b_33
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - asttokens==3.0.1
      - bokeh==3.8.1
      - click==8.3.1
      - cloudpickle==3.1.2
      - colorama==0.4.6
      - comm==0.2.3
      - contourpy==1.3.2
      - cycler==0.12.1
      - dask==2025.12.0
      - debugpy==1.8.19
      - decorator==5.2.1
      - discretize==0.11.3
      - distributed==2025.12.0
      - emcee==3.1.6
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - fonttools==4.61.1
      - fsspec==2025.12.0
      - geoana==0.7.2
      - gstools==1.7.0
      - gstools-cython==1.1.0
      - hankel==1.2.2
      - importlib-metadata==8.7.0
      - ipykernel==7.1.0
      - ipython==8.37.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - jupyter-client==8.7.0
      - jupyter-core==5.9.1
      - kiwisolver==1.4.9
      - libdlf==0.3.0
      - locket==1.0.0
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - meshio==5.3.5
      - mpmath==1.3.0
      - msgpack==1.1.2
      - narwhals==2.14.0
      - nest-asyncio==1.6.0
      - numpy==2.2.6
      - packaging==25.0
      - pandas==2.3.3
      - parso==0.8.5
      - partd==1.4.2
      - pillow==12.0.0
      - platformdirs==4.5.1
      - prompt-toolkit==3.0.52
      - psutil==7.1.3
      - pure-eval==0.2.3
      - pyevtk==1.6.0
      - pygments==2.19.2
      - pymatsolver==0.4.0
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - rich==14.2.0
      - scipy==1.15.3
      - simpeg==0.24.0
      - six==1.17.0
      - sortedcontainers==2.4.0
      - stack-data==0.6.3
      - tblib==3.2.2
      - toolz==1.1.0
      - tornado==6.5.4
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - urllib3==2.6.2
      - wcwidth==0.2.14
      - xyzservices==2025.11.0
      - zict==3.0.0
      - zipp==3.23.0
